#!/bin/bash

## Environment checking dependent on init.sh being run ...
if [[ "$DOCKTIE_INIT" = "true" ]] && [[ -e $DOCKTIE_ENV ]]; then
    . $DOCKTIE_ENV

    DOCKER_COMPOSE_BIN="docker-compose -f $DOCKTIE_DOCKER_COMPOSE_FULLPATH"
else
    echo 'ERROR: DockTie needs to be initialized.'
    exit 1 
fi

## Environment OK, proceed...
script_name=$1
shift

SCRIPT_CONF="$(dirname $0)/conf/${script_name}.conf"
if [[ -e "$SCRIPT_CONF" ]]; then
    . $SCRIPT_CONF
else
    echo "ERROR: Unconfigured util name ($script_name). See 'conf/artisan.conf' for reference in creating one."
    echo
    exit 1;
fi

## ------
## main()
## ------
if [[ "$script_name" = "composer" ]]; then
   $DOCKER_COMPOSE_BIN run --rm $docker_service_name $*
else
   if [[ $# -eq 0 ]] && [[ "$script_name" != "shell" ]] ; then
      echo "ERROR: parameter to '$script_name' missing."
      echo
      exit 1
   else
      DOCKER_CONTAINER="$DOCKER_COMPOSE_BIN exec $docker_service_name"
      $DOCKER_CONTAINER $command_within_service $*
   fi
fi
